In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import os
files = os.listdir(
    "/content/drive/MyDrive/Colab Notebooks/output/statistics"
)
files

['sampled_all_systems.csv',
 'concat_flaml.csv',
 'concat_ag.csv',
 'concat_rf.csv',
 'hpo_all_systems.csv',
 'result_equal_monotonic_rf_equal.csv',
 'result_monotonic_rf_equal.csv',
 'result_equal_monotonic_flaml_equal.csv',
 'result_monotonic_flaml_equal.csv',
 'result_equal_monotonic_ag_equal.csv',
 'result_monotonic_ag_equal.csv',
 'result_monotonic_llama.csv',
 'result_monotonic_mistral.csv',
 'llama.csv',
 'mistral.csv']

# AutoGluon

In [ ]:
system = "ag"
system_map = {
    "rf": "Random Forest with Random Search",
    "ag": "AutoGluon",
    "flaml": "FLAML",
}

## HPO

In [ ]:
hpo = pd.read_csv(
    "/content/drive/MyDrive/Colab Notebooks/output/statistics/hpo_all_systems.csv",
    sep=";"
)
hpo = hpo[hpo["automl_system"] == system_map[system]]
hpo["are_concat_pred_equal"] = hpo.apply(
    lambda row: row["trained_dataset"] == row["predicted_dataset"],
    axis=1
)
equal_hpo = hpo[hpo["are_concat_pred_equal"]]
diff_hpo = hpo[~(hpo["are_concat_pred_equal"])]

In [ ]:
# Looking at one HPO equal dataset example
equal_hpo.query("trained_dataset == 'ua_01'")

,trained_dataset,predicted_dataset,automl_system,method,percentage,missing_in_pred,extra_in_pred,only_one_predicted_label,f1_micro_majority,hold_out_f1_score,y_true_labels,y_pred_labels,are_concat_pred_equal
323,ua_01,ua_01,AutoGluon,gmm_random,100,[],[],False,0.55838,0.658105,"['3', '10', '1', '7', '5']","['3', '10', '1', '7', '5']",True

In [ ]:
# Looking at diff HPO equal dataset example
diff_hpo.query("trained_dataset == 'ua_01'")

,trained_dataset,predicted_dataset,automl_system,method,percentage,missing_in_pred,extra_in_pred,only_one_predicted_label,f1_micro_majority,hold_out_f1_score,y_true_labels,y_pred_labels,are_concat_pred_equal
322,ua_01,ua_03,AutoGluon,gmm_random,100,[],[],False,0.666016,0.630244,"['10', '3', '1', '7', '5']","['3', '10', '1', '7', '5']",False

## Concat

In [ ]:
automl_concat_df = pd.read_csv(
    f"/content/drive/MyDrive/Colab Notebooks/output/statistics/concat_{system}.csv",
    sep=";"
)

adapt_mask = automl_concat_df["concatenated_dataset"] == automl_concat_df["predicted_dataset"]
aug_mask = automl_concat_df["trained_dataset"] == automl_concat_df["predicted_dataset"]

equal_concat_df = automl_concat_df.loc[adapt_mask & (~aug_mask)]
diff_concat_df = automl_concat_df.loc[(~adapt_mask) & (~aug_mask)]

In [ ]:
# Looking at one equal concat dataset example
equal_concat_df.query("trained_dataset == 'ua_01'")

,trained_dataset,predicted_dataset,concatenated_dataset,automl_system,method,percentage,missing_in_pred,extra_in_pred,only_one_predicted_label,f1_micro_majority,hold_out_f1_score,y_true_labels,y_pred_labels
1651,ua_01,ua_03,ua_03,AutoGluon,gmm_random,25,['3'],[],False,0.666016,0.661789,"['3', '5', '10', '1', '7']","['5', '1', '10', '7']"
1656,ua_01,ua_03,ua_03,AutoGluon,gmm_random,50,[],[],False,0.666016,0.668618,"['3', '5', '10', '1', '7']","['3', '5', '10', '1', '7']"
1661,ua_01,ua_03,ua_03,AutoGluon,gmm_random,75,['3'],[],False,0.666016,0.659837,"['3', '5', '10', '1', '7']","['5', '1', '10', '7']"
1667,ua_01,ua_04,ua_04,AutoGluon,gmm_random,25,[],[],False,0.200040,0.483397,"['3', '5', '10', '1', '7']","['3', '5', '10', '1', '7']"
1672,ua_01,ua_04,ua_04,AutoGluon,gmm_random,50,[],[],False,0.200040,0.483597,"['3', '5', '10', '1', '7']","['3', '5', '10', '1', '7']"
1677,ua_01,ua_04,ua_04,AutoGluon,gmm_random,75,[],[],False,0.200040,0.488398,"['3', '5', '10', '1', '7']","['3', '5', '10', '1', '7']"
1683,ua_01,ua_05,ua_05,AutoGluon,gmm_random,25,['3'],[],False,0.776119,0.763682,"['3', '5', '10', '1', '7']","['7', '5', '10', '1']"
1688,ua_01,ua_05,ua_05,AutoGluon,gmm_random,50,['3'],[],False,0.776119,0.763682,"['3', '5', '10', '1', '7']","['7', '5', '10', '1']"
1693,ua_01,ua_05,ua_05,AutoGluon,gmm_random,75,['3'],[],False,0.776119,0.783582,"['3', '5', '10', '1', '7']","['7', '5', '10', '1']"
1699,ua_01,ua_06,ua_06,AutoGluon,gmm_random,25,[],[],False,0.442095,0.565875,"['3', '5', '10', '1', '7']","['3', '5', '10', '1', '7']"
1704,ua_01,ua_06,ua_06,AutoGluon,gmm_random,50,[],[],False,0.442095,0.576773,"['3', '5', '10', '1', '7']","['3', '5', '10', '1', '7']"
1709,ua_01,ua_06,ua_06,AutoGluon,gmm_random,75,[],[],False,0.442095,0.584092,"['3', '5', '10', '1', '7']","['3', '5', '10', '1', '7']"

In [ ]:
# Looking at one diff concat dataset example
diff_concat_df.query("trained_dataset == 'ua_01'")

,trained_dataset,predicted_dataset,concatenated_dataset,automl_system,method,percentage,missing_in_pred,extra_in_pred,only_one_predicted_label,f1_micro_majority,hold_out_f1_score,y_true_labels,y_pred_labels
1652,ua_01,ua_04,ua_03,AutoGluon,gmm_random,25,[],[],False,0.200040,0.368074,"['3', '5', '10', '1', '7']","['3', '5', '10', '1', '7']"
1653,ua_01,ua_05,ua_03,AutoGluon,gmm_random,25,['3'],[],False,0.776119,0.686567,"['3', '5', '10', '1', '7']","['7', '5', '10', '1']"
1654,ua_01,ua_06,ua_03,AutoGluon,gmm_random,25,['3'],[],False,0.442095,0.480481,"['3', '5', '10', '1', '7']","['7', '5', '10', '1']"
1657,ua_01,ua_04,ua_03,AutoGluon,gmm_random,50,[],[],False,0.200040,0.362973,"['3', '5', '10', '1', '7']","['3', '5', '10', '1', '7']"
1658,ua_01,ua_05,ua_03,AutoGluon,gmm_random,50,['3'],[],False,0.776119,0.686567,"['3', '5', '10', '1', '7']","['7', '5', '10', '1']"
1659,ua_01,ua_06,ua_03,AutoGluon,gmm_random,50,"['3', '5', '7']",[],False,0.442095,0.461451,"['3', '5', '10', '1', '7']","['10', '1']"
1662,ua_01,ua_04,ua_03,AutoGluon,gmm_random,75,[],[],False,0.200040,0.351270,"['3', '5', '10', '1', '7']","['3', '5', '10', '1', '7']"
1663,ua_01,ua_05,ua_03,AutoGluon,gmm_random,75,['3'],[],False,0.776119,0.671642,"['3', '5', '10', '1', '7']","['7', '5', '10', '1']"
1664,ua_01,ua_06,ua_03,AutoGluon,gmm_random,75,"['3', '5', '7']",[],False,0.442095,0.468445,"['3', '5', '10', '1', '7']","['10', '1']"
1666,ua_01,ua_03,ua_04,AutoGluon,gmm_random,25,[],[],False,0.666016,0.513171,"['3', '5', '10', '1', '7']","['3', '5', '10', '1', '7']"
1668,ua_01,ua_05,ua_04,AutoGluon,gmm_random,25,['3'],[],False,0.776119,0.639303,"['3', '5', '10', '1', '7']","['7', '5', '10', '1']"
1669,ua_01,ua_06,ua_04,AutoGluon,gmm_random,25,[],[],False,0.442095,0.486174,"['3', '5', '10', '1', '7']","['3', '5', '10', '1', '7']"
1671,ua_01,ua_03,ua_04,AutoGluon,gmm_random,50,[],[],False,0.666016,0.462114,"['3', '5', '10', '1', '7']","['3', '5', '10', '1', '7']"
1673,ua_01,ua_05,ua_04,AutoGluon,gmm_random,50,['3'],[],False,0.776119,0.624378,"['3', '5', '10', '1', '7']","['7', '5', '10', '1']"
1674,ua_01,ua_06,ua_04,AutoGluon,gmm_random,50,[],[],False,0.442095,0.480644,"['3', '5', '10', '1', '7']","['3', '5', '10', '1', '7']"
1676,ua_01,ua_03,ua_04,AutoGluon,gmm_random,75,[],[],False,0.666016,0.510894,"['3', '5', '10', '1', '7']","['3', '5', '10', '1', '7']"
1678,ua_01,ua_05,ua_04,AutoGluon,gmm_random,75,['3'],[],False,0.776119,0.659204,"['3', '5', '10', '1', '7']","['7', '5', '10', '1']"
1679,ua_01,ua_06,ua_04,AutoGluon,gmm_random,75,"['3', '7']",[],False,0.442095,0.487476,"['3', '5', '10', '1', '7']","['5', '10', '1']"
1681,ua_01,ua_03,ua_05,AutoGluon,gmm_random,25,[],[],False,0.666016,0.629268,"['3', '5', '10', '1', '7']","['3', '5', '10', '1', '7']"
1682,ua_01,ua_04,ua_05,AutoGluon,gmm_random,25,[],[],False,0.200040,0.350270,"['3', '5', '10', '1', '7']","['3', '5', '10', '1', '7']"
1684,ua_01,ua_06,ua_05,AutoGluon,gmm_random,25,"['3', '5', '7']",[],False,0.442095,0.465517,"['3', '5', '10', '1', '7']","['10', '1']"
1686,ua_01,ua_03,ua_05,AutoGluon,gmm_random,50,[],[],False,0.666016,0.630569,"['3', '5', '10', '1', '7']","['3', '5', '10', '1', '7']"
1687,ua_01,ua_04,ua_05,AutoGluon,gmm_random,50,[],[],False,0.200040,0.331966,"['3', '5', '10', '1', '7']","['3', '5', '10', '1', '7']"
1689,ua_01,ua_06,ua_05,AutoGluon,gmm_random,50,"['3', '7']",[],False,0.442095,0.458523,"['3', '5', '10', '1', '7']","['5', '10', '1']"
1691,ua_01,ua_03,ua_05,AutoGluon,gmm_random,75,[],[],False,0.666016,0.631545,"['3', '5', '10', '1', '7']","['3', '5', '10', '1', '7']"
1692,ua_01,ua_04,ua_05,AutoGluon,gmm_random,75,[],[],False,0.200040,0.355671,"['3', '5', '10', '1', '7']","['3', '5', '10', '1', '7']"
1694,ua_01,ua_06,ua_05,AutoGluon,gmm_random,75,"['5', '7']",[],False,0.442095,0.465680,"['3', '5', '10', '1', '7']","['3', '10', '1']"
1696,ua_01,ua_03,ua_06,AutoGluon,gmm_random,25,[],[],False,0.666016,0.635122,"['3', '5', '10', '1', '7']","['3', '5', '10', '1', '7']"
1697,ua_01,ua_04,ua_06,AutoGluon,gmm_random,25,[],[],False,0.200040,0.360072,"['3', '5', '10', '1', '7']","['3', '5', '10', '1', '7']"
1698,ua_01,ua_05,ua_06,AutoGluon,gmm_random,25,[],[],False,0.776119,0.656716,"['3', '5', '10', '1', '7']","['3', '5', '10', '1', '7']"
1701,ua_01,ua_03,ua_06,AutoGluon,gmm_random,50,[],[],False,0.666016,0.607480,"['3', '5', '10', '1', '7']","['3', '5', '10', '1', '7']"
1702,ua_01,ua_04,ua_06,AutoGluon,gmm_random,50,[],[],False,0.200040,0.367774,"['3', '5', '10', '1', '7']","['3', '5', '10', '1', '7']"
1703,ua_01,ua_05,ua_06,AutoGluon,gmm_random,50,['3'],[],False,0.776119,0.649254,"['3', '5', '10', '1', '7']","['7', '5', '10', '1']"
1706,ua_01,ua_03,ua_06,AutoGluon,gmm_random,75,[],[],False,0.666016,0.603902,"['3', '5', '10', '1', '7']","['3', '5', '10', '1', '7']"
1707,ua_01,ua_04,ua_06,AutoGluon,gmm_random,75,[],[],False,0.200040,0.375675,"['3', '5', '10', '1', '7']","['3', '5', '10', '1', '7']"
1708,ua_01,ua_05,ua_06,AutoGluon,gmm_random,75,['3'],[],False,0.776119,0.671642,"['3', '5', '10', '1', '7']","['7', '5', '10', '1']"

## Equal

### 25, 50, 75

In [ ]:
grouped_equal_concat_df = (
    equal_concat_df.groupby(
        [
            "predicted_dataset",
            "automl_system",
            "method",
            "percentage"
        ]
    )
    .agg(
        {
            "hold_out_f1_score": "mean"
        }
    )
)
grouped_equal_concat_df = grouped_equal_concat_df.reset_index()
grouped_equal_concat_df

    predicted_dataset automl_system      method  percentage  hold_out_f1_score
0               ed_01     AutoGluon  gmm_random          25           0.132780
1               ed_01     AutoGluon  gmm_random          50           0.302905
2               ed_01     AutoGluon  gmm_random          75           0.294606
3               ed_02     AutoGluon  gmm_random          25           0.667767
4               ed_02     AutoGluon  gmm_random          50           0.638624
..                ...           ...         ...         ...                ...
100             ua_05     AutoGluon  gmm_random          50           0.766667
101             ua_05     AutoGluon  gmm_random          75           0.787065
102             ua_06     AutoGluon  gmm_random          25           0.571080
103             ua_06     AutoGluon  gmm_random          50           0.576350
104             ua_06     AutoGluon  gmm_random          75           0.585817

[105 rows x 5 columns]

### 0%

In [ ]:
grouped_zero_pct_hpo = (
    diff_hpo.groupby(
        [
            "predicted_dataset",
            "automl_system",
            "method"
        ]
    )
    .agg(
        {
            "hold_out_f1_score": "mean"
        }
    )
)
grouped_zero_pct_hpo = grouped_zero_pct_hpo.reset_index()
grouped_zero_pct_hpo["percentage"] = 0
grouped_zero_pct_hpo

   predicted_dataset automl_system      method  hold_out_f1_score  percentage
0              ed_01     AutoGluon  gmm_random           0.020747           0
1              fn_02     AutoGluon  gmm_random           0.344444           0
2              fn_06     AutoGluon  gmm_random           0.362869           0
3              fn_07     AutoGluon  gmm_random           0.394886           0
4              fn_09     AutoGluon  gmm_random           0.285834           0
5              fn_10     AutoGluon  gmm_random           0.366667           0
6              hs_01     AutoGluon  gmm_random           0.450348           0
7              hs_02     AutoGluon  gmm_random           0.314387           0
8              hs_03     AutoGluon  gmm_random           0.584734           0
9              hs_04     AutoGluon  gmm_random           0.830148           0
10             hs_06     AutoGluon  gmm_random           0.588944           0
11             hs_08     AutoGluon  gmm_random           0.816324           0
12             hs_09     AutoGluon  gmm_random           0.842219           0
13             hs_10     AutoGluon  gmm_random           0.602222           0
14             hs_11     AutoGluon  gmm_random           0.472141           0
15             hs_12     AutoGluon  gmm_random           0.441441           0
16             hs_13     AutoGluon  gmm_random           0.366925           0
17             hs_14     AutoGluon  gmm_random           0.574561           0
18             pc_01     AutoGluon  gmm_random           0.525567           0
19             pc_02     AutoGluon  gmm_random           0.595963           0
20             pc_03     AutoGluon  gmm_random           0.591593           0
21             pc_04     AutoGluon  gmm_random           0.593892           0
22             pc_05     AutoGluon  gmm_random           0.467868           0
23             pc_06     AutoGluon  gmm_random           0.615353           0
24             pc_07     AutoGluon  gmm_random           0.504801           0
25             pc_08     AutoGluon  gmm_random           0.371456           0
26             sd_03     AutoGluon  gmm_random           0.333333           0
27             sd_04     AutoGluon  gmm_random           0.370667           0
28             ua_01     AutoGluon  gmm_random           0.552515           0
29             ua_03     AutoGluon  gmm_random           0.608699           0
30             ua_04     AutoGluon  gmm_random           0.236497           0
31             ua_05     AutoGluon  gmm_random           0.657960           0
32             ua_06     AutoGluon  gmm_random           0.438842           0

### 100%

In [ ]:
# There is only one point per dataset since trained = predicted, but we are still grouping by and determining the mean for consistency
grouped_100_pct_hpo = (
    equal_hpo.groupby(
        [
            "predicted_dataset",
            "automl_system",
            "method"
        ]
    )
    .agg(
        {
            "hold_out_f1_score": "mean"
        }
    )
)
grouped_100_pct_hpo = grouped_100_pct_hpo.reset_index()
grouped_100_pct_hpo["percentage"] = 100
grouped_100_pct_hpo

   predicted_dataset automl_system      method  hold_out_f1_score  percentage
0              ed_01     AutoGluon  gmm_random           0.468880         100
1              ed_02     AutoGluon  gmm_random           0.766363         100
2              ed_03     AutoGluon  gmm_random           0.470735         100
3              ed_04     AutoGluon  gmm_random           0.925421         100
4              ed_05     AutoGluon  gmm_random           0.375000         100
5              fn_01     AutoGluon  gmm_random           0.267238         100
6              fn_02     AutoGluon  gmm_random           0.500000         100
7              fn_03     AutoGluon  gmm_random           0.267678         100
8              fn_04     AutoGluon  gmm_random           0.559633         100
9              fn_05     AutoGluon  gmm_random           0.538171         100
10             fn_06     AutoGluon  gmm_random           0.459916         100
11             fn_07     AutoGluon  gmm_random           0.522727         100
12             fn_08     AutoGluon  gmm_random           0.843008         100
13             fn_09     AutoGluon  gmm_random           0.471081         100
14             fn_10     AutoGluon  gmm_random           0.583333         100
15             hs_01     AutoGluon  gmm_random           0.834915         100
16             hs_02     AutoGluon  gmm_random           0.848792         100
17             hs_03     AutoGluon  gmm_random           0.768908         100
18             hs_04     AutoGluon  gmm_random           0.925574         100
19             hs_05     AutoGluon  gmm_random           0.774467         100
20             hs_06     AutoGluon  gmm_random           0.579677         100
21             hs_07     AutoGluon  gmm_random           0.795991         100
22             hs_08     AutoGluon  gmm_random           0.956007         100
23             hs_09     AutoGluon  gmm_random           0.949919         100
24             hs_10     AutoGluon  gmm_random           0.700000         100
25             hs_11     AutoGluon  gmm_random           0.832845         100
26             hs_12     AutoGluon  gmm_random           0.675676         100
27             hs_13     AutoGluon  gmm_random           0.826873         100
28             hs_14     AutoGluon  gmm_random           0.960526         100
29             hs_15     AutoGluon  gmm_random           0.842969         100
30             pc_01     AutoGluon  gmm_random           0.783184         100
31             pc_02     AutoGluon  gmm_random           0.694051         100
32             pc_03     AutoGluon  gmm_random           0.841734         100
33             pc_04     AutoGluon  gmm_random           0.860282         100
34             pc_05     AutoGluon  gmm_random           0.573810         100
35             pc_06     AutoGluon  gmm_random           0.881172         100
36             pc_07     AutoGluon  gmm_random           0.835391         100
37             pc_08     AutoGluon  gmm_random           0.483202         100
38             pc_09     AutoGluon  gmm_random           0.774038         100
39             sd_01     AutoGluon  gmm_random           0.817708         100
40             sd_02     AutoGluon  gmm_random           0.840461         100
41             sd_03     AutoGluon  gmm_random           0.610667         100
42             sd_04     AutoGluon  gmm_random           0.624000         100
43             ua_01     AutoGluon  gmm_random           0.658105         100
44             ua_02     AutoGluon  gmm_random           0.251714         100
45             ua_03     AutoGluon  gmm_random           0.666667         100
46             ua_04     AutoGluon  gmm_random           0.517804         100
47             ua_05     AutoGluon  gmm_random           0.788557         100
48             ua_06     AutoGluon  gmm_random           0.588321         100

### Result

In [ ]:
result_equal = (
    pd.concat(
        [
            grouped_equal_concat_df,
            grouped_zero_pct_hpo,
            grouped_100_pct_hpo
        ],
        axis=0
    )
    .sort_values(
        [
            "predicted_dataset",
            "automl_system",
            "method",
            "percentage"
        ]
    )
)
monotonic_equal = (
    result_equal.sort_values(
        [
            "predicted_dataset",
            "automl_system",
            "method",
            "percentage"
        ]
    )
    .groupby(
        [
            "predicted_dataset",
            "automl_system",
            "method"
        ],
        as_index=False,
        observed=True
    )
    ["hold_out_f1_score"]
    .apply(lambda x: x.is_monotonic_increasing)
    .rename(columns={"hold_out_f1_score": "is_monotonic_increasing"})
    [["predicted_dataset", "automl_system", "method", "is_monotonic_increasing"]]
)
result_equal = (
    result_equal.merge(
        monotonic_equal,
        on=["predicted_dataset", "automl_system", "method"],
    )
    .sort_values(["predicted_dataset", "automl_system", "method", "percentage"])
)

value_counts = result_equal["predicted_dataset"].value_counts()

assert value_counts[(value_counts > 1) & (value_counts < 4)].empty, "There should not be any dataset with 2-3 data points"

isolated = value_counts[value_counts == 1].index
assert ~grouped_equal_concat_df["predicted_dataset"].isin(isolated).any(), "There should not be any isolated datasets in concatenated datasets"
assert ~grouped_zero_pct_hpo["predicted_dataset"].isin(isolated).any(), "There should not be any isolated datasets in HPO's 0 pct"
assert (set(isolated) - set(grouped_100_pct_hpo["predicted_dataset"].unique())) == set()

result_equal = result_equal[~result_equal["predicted_dataset"].isin(isolated)]
result_equal.to_csv(
    f"/content/drive/MyDrive/Colab Notebooks/output/statistics/result_equal_monotonic_{system}_equal.csv",
    sep=";"
)
result_equal

,predicted_dataset,automl_system,method,percentage,hold_out_f1_score,is_monotonic_increasing
0,ed_01,AutoGluon,gmm_random,0,0.020747,False
1,ed_01,AutoGluon,gmm_random,25,0.132780,False
2,ed_01,AutoGluon,gmm_random,50,0.302905,False
3,ed_01,AutoGluon,gmm_random,75,0.294606,False
4,ed_01,AutoGluon,gmm_random,100,0.468880,False
...,...,...,...,...,...,...
182,ua_06,AutoGluon,gmm_random,0,0.438842,True
183,ua_06,AutoGluon,gmm_random,25,0.571080,True
184,ua_06,AutoGluon,gmm_random,50,0.576350,True
185,ua_06,AutoGluon,gmm_random,75,0.585817,True
186,ua_06,AutoGluon,gmm_random,100,0.588321,True

## Diff

### 25, 50, 75

In [ ]:
grouped_diff_concat_df = (
    diff_concat_df.groupby(
        [
            "predicted_dataset",
            "automl_system",
            "method",
            "percentage"
        ]
    )
    .agg(
        {
            "hold_out_f1_score": "mean"
        }
    )
)
grouped_diff_concat_df = grouped_diff_concat_df.reset_index()
grouped_diff_concat_df

   predicted_dataset automl_system      method  percentage  hold_out_f1_score
0              ed_01     AutoGluon  gmm_random          25           0.012448
1              ed_01     AutoGluon  gmm_random          50           0.020747
2              ed_01     AutoGluon  gmm_random          75           0.037344
3              ed_02     AutoGluon  gmm_random          25           0.107823
4              ed_02     AutoGluon  gmm_random          50           0.147415
..               ...           ...         ...         ...                ...
70             ua_05     AutoGluon  gmm_random          50           0.627488
71             ua_05     AutoGluon  gmm_random          75           0.616449
72             ua_06     AutoGluon  gmm_random          25           0.467510
73             ua_06     AutoGluon  gmm_random          50           0.465355
74             ua_06     AutoGluon  gmm_random          75           0.467245

[75 rows x 5 columns]

### 0%

In [ ]:
grouped_zero_pct_hpo = (
      diff_hpo.groupby(
          [
              "predicted_dataset",
              "automl_system",
              "method"
          ]
      )
      .agg(
          {
              "hold_out_f1_score": "mean"
          }
      )
)
grouped_zero_pct_hpo = grouped_zero_pct_hpo.reset_index()
grouped_zero_pct_hpo["percentage"] = 0
grouped_zero_pct_hpo

   predicted_dataset automl_system      method  hold_out_f1_score  percentage
0              ed_01     AutoGluon  gmm_random           0.020747           0
1              fn_02     AutoGluon  gmm_random           0.344444           0
2              fn_06     AutoGluon  gmm_random           0.362869           0
3              fn_07     AutoGluon  gmm_random           0.394886           0
4              fn_09     AutoGluon  gmm_random           0.285834           0
5              fn_10     AutoGluon  gmm_random           0.366667           0
6              hs_01     AutoGluon  gmm_random           0.450348           0
7              hs_02     AutoGluon  gmm_random           0.314387           0
8              hs_03     AutoGluon  gmm_random           0.584734           0
9              hs_04     AutoGluon  gmm_random           0.830148           0
10             hs_06     AutoGluon  gmm_random           0.588944           0
11             hs_08     AutoGluon  gmm_random           0.816324           0
12             hs_09     AutoGluon  gmm_random           0.842219           0
13             hs_10     AutoGluon  gmm_random           0.602222           0
14             hs_11     AutoGluon  gmm_random           0.472141           0
15             hs_12     AutoGluon  gmm_random           0.441441           0
16             hs_13     AutoGluon  gmm_random           0.366925           0
17             hs_14     AutoGluon  gmm_random           0.574561           0
18             pc_01     AutoGluon  gmm_random           0.525567           0
19             pc_02     AutoGluon  gmm_random           0.595963           0
20             pc_03     AutoGluon  gmm_random           0.591593           0
21             pc_04     AutoGluon  gmm_random           0.593892           0
22             pc_05     AutoGluon  gmm_random           0.467868           0
23             pc_06     AutoGluon  gmm_random           0.615353           0
24             pc_07     AutoGluon  gmm_random           0.504801           0
25             pc_08     AutoGluon  gmm_random           0.371456           0
26             sd_03     AutoGluon  gmm_random           0.333333           0
27             sd_04     AutoGluon  gmm_random           0.370667           0
28             ua_01     AutoGluon  gmm_random           0.552515           0
29             ua_03     AutoGluon  gmm_random           0.608699           0
30             ua_04     AutoGluon  gmm_random           0.236497           0
31             ua_05     AutoGluon  gmm_random           0.657960           0
32             ua_06     AutoGluon  gmm_random           0.438842           0

### 100%

In [ ]:
# There is only one point per dataset since trained = predicted, but we are still grouping by and determining the mean for consistency
grouped_100_pct_hpo = (
    equal_hpo.groupby(
        [
            "predicted_dataset",
            "automl_system",
            "method"
        ]
    )
    .agg(
        {
            "hold_out_f1_score": "mean"
        }
    )
)
grouped_100_pct_hpo = grouped_100_pct_hpo.reset_index()
grouped_100_pct_hpo["percentage"] = 100
grouped_100_pct_hpo

   predicted_dataset automl_system      method  hold_out_f1_score  percentage
0              ed_01     AutoGluon  gmm_random           0.468880         100
1              ed_02     AutoGluon  gmm_random           0.766363         100
2              ed_03     AutoGluon  gmm_random           0.470735         100
3              ed_04     AutoGluon  gmm_random           0.925421         100
4              ed_05     AutoGluon  gmm_random           0.375000         100
5              fn_01     AutoGluon  gmm_random           0.267238         100
6              fn_02     AutoGluon  gmm_random           0.500000         100
7              fn_03     AutoGluon  gmm_random           0.267678         100
8              fn_04     AutoGluon  gmm_random           0.559633         100
9              fn_05     AutoGluon  gmm_random           0.538171         100
10             fn_06     AutoGluon  gmm_random           0.459916         100
11             fn_07     AutoGluon  gmm_random           0.522727         100
12             fn_08     AutoGluon  gmm_random           0.843008         100
13             fn_09     AutoGluon  gmm_random           0.471081         100
14             fn_10     AutoGluon  gmm_random           0.583333         100
15             hs_01     AutoGluon  gmm_random           0.834915         100
16             hs_02     AutoGluon  gmm_random           0.848792         100
17             hs_03     AutoGluon  gmm_random           0.768908         100
18             hs_04     AutoGluon  gmm_random           0.925574         100
19             hs_05     AutoGluon  gmm_random           0.774467         100
20             hs_06     AutoGluon  gmm_random           0.579677         100
21             hs_07     AutoGluon  gmm_random           0.795991         100
22             hs_08     AutoGluon  gmm_random           0.956007         100
23             hs_09     AutoGluon  gmm_random           0.949919         100
24             hs_10     AutoGluon  gmm_random           0.700000         100
25             hs_11     AutoGluon  gmm_random           0.832845         100
26             hs_12     AutoGluon  gmm_random           0.675676         100
27             hs_13     AutoGluon  gmm_random           0.826873         100
28             hs_14     AutoGluon  gmm_random           0.960526         100
29             hs_15     AutoGluon  gmm_random           0.842969         100
30             pc_01     AutoGluon  gmm_random           0.783184         100
31             pc_02     AutoGluon  gmm_random           0.694051         100
32             pc_03     AutoGluon  gmm_random           0.841734         100
33             pc_04     AutoGluon  gmm_random           0.860282         100
34             pc_05     AutoGluon  gmm_random           0.573810         100
35             pc_06     AutoGluon  gmm_random           0.881172         100
36             pc_07     AutoGluon  gmm_random           0.835391         100
37             pc_08     AutoGluon  gmm_random           0.483202         100
38             pc_09     AutoGluon  gmm_random           0.774038         100
39             sd_01     AutoGluon  gmm_random           0.817708         100
40             sd_02     AutoGluon  gmm_random           0.840461         100
41             sd_03     AutoGluon  gmm_random           0.610667         100
42             sd_04     AutoGluon  gmm_random           0.624000         100
43             ua_01     AutoGluon  gmm_random           0.658105         100
44             ua_02     AutoGluon  gmm_random           0.251714         100
45             ua_03     AutoGluon  gmm_random           0.666667         100
46             ua_04     AutoGluon  gmm_random           0.517804         100
47             ua_05     AutoGluon  gmm_random           0.788557         100
48             ua_06     AutoGluon  gmm_random           0.588321         100

### Result

In [ ]:
result_diff = (
    pd.concat(
        [
            grouped_diff_concat_df,
            grouped_zero_pct_hpo,
            grouped_100_pct_hpo
        ],
        axis=0
    )
    .sort_values(["predicted_dataset", "automl_system", "method", "percentage"])
)
monotonic_diff = (
    result_diff.sort_values(["predicted_dataset", "automl_system", "method", "percentage"])
    .groupby(
        [
            "predicted_dataset",
            "automl_system",
            "method"
        ],
        as_index=False, observed=True
    )
    ["hold_out_f1_score"]
    .apply(lambda x: x.is_monotonic_increasing)
    .rename(columns={"hold_out_f1_score": "is_monotonic_increasing"})
    [["predicted_dataset", "automl_system", "method", "is_monotonic_increasing"]]
)
result_diff = (
    result_diff.merge(
        monotonic_diff,
        on=["predicted_dataset", "automl_system", "method"],
    )
    .sort_values(["predicted_dataset", "automl_system", "method", "percentage"])
)

value_counts = result_diff["predicted_dataset"].value_counts()

# assert value_counts[(value_counts > 1) & (value_counts < 4)].empty, "There should not be any dataset with 2-3 data points"

isolated = value_counts[value_counts == 1].index
assert (~grouped_equal_concat_df["predicted_dataset"].isin(isolated)).any(), "There should not be any isolated datasets in concatenated datasets"
assert (~grouped_zero_pct_hpo["predicted_dataset"].isin(isolated)).any(), "There should not be any isolated datasets in HPO's 0 pct"
assert (set(isolated) - set(grouped_100_pct_hpo["predicted_dataset"].unique())) == set()

result_diff = result_diff[~result_diff["predicted_dataset"].isin(isolated)]
result_diff.to_csv(
    f"/content/drive/MyDrive/Colab Notebooks/output/statistics/result_monotonic_{system}_equal.csv",
    sep=";"
)
result_diff

,predicted_dataset,automl_system,method,percentage,hold_out_f1_score,is_monotonic_increasing
0,ed_01,AutoGluon,gmm_random,0,0.020747,False
1,ed_01,AutoGluon,gmm_random,25,0.012448,False
2,ed_01,AutoGluon,gmm_random,50,0.020747,False
3,ed_01,AutoGluon,gmm_random,75,0.037344,False
4,ed_01,AutoGluon,gmm_random,100,0.468880,False
...,...,...,...,...,...,...
152,ua_06,AutoGluon,gmm_random,0,0.438842,False
153,ua_06,AutoGluon,gmm_random,25,0.467510,False
154,ua_06,AutoGluon,gmm_random,50,0.465355,False
155,ua_06,AutoGluon,gmm_random,75,0.467245,False
156,ua_06,AutoGluon,gmm_random,100,0.588321,False

# Analysis Examples

Some examples of interesting analysis below:

## Monotonic Analysis

### Equal count

In [ ]:
is_monotonic_increasing_equal = result_equal["is_monotonic_increasing"]

monotonic_increasing_equal = result_equal.loc[is_monotonic_increasing_equal]
non_monotonic_increasing_equal = result_equal.loc[~is_monotonic_increasing_equal]

print(f"Number EQUAL Monotonic increasing: {len(monotonic_increasing_equal.drop_duplicates('predicted_dataset'))}")
print(f"{monotonic_increasing_equal['predicted_dataset'].drop_duplicates().to_list()}")

print(f"Number EQUAL Non-monotonic increasing: {len(non_monotonic_increasing_equal.drop_duplicates('predicted_dataset'))}")
print(f"{non_monotonic_increasing_equal['predicted_dataset'].drop_duplicates().to_list()}")

Number EQUAL Monotonic increasing: 19
['fn_07', 'fn_10', 'hs_02', 'hs_03', 'hs_04', 'hs_08', 'hs_09', 'hs_11', 'hs_12', 'hs_13', 'hs_14', 'pc_01', 'pc_03', 'sd_03', 'sd_04', 'ua_01', 'ua_04', 'ua_05', 'ua_06']
Number EQUAL Non-monotonic increasing: 16
['ed_01', 'ed_02', 'fn_02', 'fn_05', 'fn_06', 'fn_09', 'hs_01', 'hs_06', 'hs_10', 'pc_02', 'pc_04', 'pc_05', 'pc_06', 'pc_07', 'pc_08', 'ua_03']

### Diff count

In [ ]:
is_monotonic_increasing_diff = result_diff["is_monotonic_increasing"]

monotonic_increasing_diff = result_diff.loc[is_monotonic_increasing_diff]
non_monotonic_increasing_diff = result_diff.loc[~is_monotonic_increasing_diff]

print(f"Number diff Monotonic increasing: {len(monotonic_increasing_diff.drop_duplicates('predicted_dataset'))}")
print(f"{monotonic_increasing_diff['predicted_dataset'].drop_duplicates().to_list()}")

print(f"Number diff Non-monotonic increasing: {len(non_monotonic_increasing_diff.drop_duplicates('predicted_dataset'))}")
print(f"{non_monotonic_increasing_diff['predicted_dataset'].drop_duplicates().to_list()}")

Number diff Monotonic increasing: 13
['fn_02', 'fn_07', 'fn_09', 'fn_10', 'hs_01', 'hs_04', 'hs_08', 'hs_11', 'hs_14', 'sd_03', 'sd_04', 'ua_01', 'ua_04']
Number diff Non-monotonic increasing: 21
['ed_01', 'ed_02', 'fn_06', 'hs_02', 'hs_03', 'hs_06', 'hs_09', 'hs_10', 'hs_12', 'hs_13', 'pc_01', 'pc_02', 'pc_03', 'pc_04', 'pc_05', 'pc_06', 'pc_07', 'pc_08', 'ua_03', 'ua_05', 'ua_06']

### Non-monotonicic equal f1_score difference

In [ ]:
(
    pd.concat(
        [
            non_monotonic_increasing_equal,
            (
                non_monotonic_increasing_equal[["hold_out_f1_score", "predicted_dataset"]]
                .shift(1)
                .rename(
                    columns={
                        "hold_out_f1_score": "hold_out_f1_score_next",
                        "predicted_dataset": "predicted_dataset_next"
                    }
                )
            )
        ],
        axis=1
    )
    .query("predicted_dataset == predicted_dataset_next")
    .assign(diff=lambda x: x["hold_out_f1_score"] - x["hold_out_f1_score_next"])
    [["predicted_dataset", "automl_system", "method", "percentage", "hold_out_f1_score", "diff"]]
    # TODO: Remove lines below
    # TODO: Analyze cases where diff is in 100
    .query("diff < 0")
    .sort_values("diff", ignore_index=True)
    # .query("predicted_dataset == 'pc_02'")
)

,predicted_dataset,automl_system,method,percentage,hold_out_f1_score,diff
0,pc_02,AutoGluon,gmm_random,100,0.694051,-0.095609
1,fn_06,AutoGluon,gmm_random,100,0.459916,-0.081857
2,fn_05,AutoGluon,gmm_random,50,0.441110,-0.078434
3,fn_02,AutoGluon,gmm_random,100,0.500000,-0.029167
4,ed_02,AutoGluon,gmm_random,50,0.638624,-0.029143
5,pc_08,AutoGluon,gmm_random,100,0.483202,-0.020967
6,pc_04,AutoGluon,gmm_random,75,0.846674,-0.020400
7,pc_06,AutoGluon,gmm_random,100,0.881172,-0.017389
8,hs_06,AutoGluon,gmm_random,50,0.582136,-0.015129
9,pc_05,AutoGluon,gmm_random,100,0.573810,-0.010935
10,hs_01,AutoGluon,gmm_random,75,0.830487,-0.010120
11,hs_06,AutoGluon,gmm_random,100,0.579677,-0.009834
12,ed_01,AutoGluon,gmm_random,75,0.294606,-0.008299
13,pc_07,AutoGluon,gmm_random,75,0.822359,-0.006173
14,pc_02,AutoGluon,gmm_random,75,0.789660,-0.006020
15,ua_03,AutoGluon,gmm_random,75,0.654959,-0.005398
16,fn_09,AutoGluon,gmm_random,100,0.471081,-0.005029
17,fn_02,AutoGluon,gmm_random,50,0.455556,-0.004167
18,hs_10,AutoGluon,gmm_random,75,0.681667,-0.004167
19,pc_04,AutoGluon,gmm_random,50,0.867074,-0.003721

### Non-monotonic diff f1_score difference

In [ ]:
(
    pd.concat(
        [
            non_monotonic_increasing_diff,
            (
                non_monotonic_increasing_diff[["hold_out_f1_score", "predicted_dataset"]]
                .shift(1)
                .rename(
                    columns={
                        "hold_out_f1_score": "hold_out_f1_score_next",
                        "predicted_dataset": "predicted_dataset_next"
                    }
                )
            )
        ],
        axis=1
    )
    .query("predicted_dataset == predicted_dataset_next")
    .assign(diff=lambda x: x["hold_out_f1_score"] - x["hold_out_f1_score_next"])
    [["predicted_dataset", "automl_system", "method", "percentage", "hold_out_f1_score", "diff"]]
    .query("diff < 0")
    .sort_values("diff", ignore_index=True)
)

,predicted_dataset,automl_system,method,percentage,hold_out_f1_score,diff
0,fn_06,AutoGluon,gmm_random,50,0.390295,-0.080169
1,fn_06,AutoGluon,gmm_random,100,0.459916,-0.053797
2,ua_05,AutoGluon,gmm_random,25,0.611940,-0.046020
3,ua_03,AutoGluon,gmm_random,25,0.570081,-0.038618
4,hs_02,AutoGluon,gmm_random,50,0.384569,-0.032537
5,pc_08,AutoGluon,gmm_random,25,0.344645,-0.026811
6,ed_02,AutoGluon,gmm_random,75,0.121949,-0.025466
7,pc_08,AutoGluon,gmm_random,75,0.324179,-0.022836
8,pc_03,AutoGluon,gmm_random,50,0.701477,-0.020723
9,pc_06,AutoGluon,gmm_random,50,0.725788,-0.018079
10,hs_09,AutoGluon,gmm_random,50,0.836187,-0.014755
11,hs_13,AutoGluon,gmm_random,50,0.437984,-0.012920
12,pc_01,AutoGluon,gmm_random,50,0.643836,-0.011630
13,hs_03,AutoGluon,gmm_random,25,0.573529,-0.011204
14,ua_05,AutoGluon,gmm_random,75,0.616449,-0.011039
15,hs_06,AutoGluon,gmm_random,25,0.578385,-0.010558
16,pc_07,AutoGluon,gmm_random,75,0.491445,-0.010180
17,pc_05,AutoGluon,gmm_random,50,0.483449,-0.009241
18,ed_01,AutoGluon,gmm_random,25,0.012448,-0.008299
19,pc_07,AutoGluon,gmm_random,25,0.497834,-0.006967
20,pc_04,AutoGluon,gmm_random,50,0.719599,-0.006708
21,pc_02,AutoGluon,gmm_random,50,0.673226,-0.006355
22,hs_03,AutoGluon,gmm_random,75,0.574790,-0.005602
23,hs_09,AutoGluon,gmm_random,75,0.831233,-0.004954
24,hs_12,AutoGluon,gmm_random,75,0.467568,-0.004505
25,ua_03,AutoGluon,gmm_random,50,0.566626,-0.003455
26,hs_10,AutoGluon,gmm_random,75,0.642444,-0.003333
27,ua_06,AutoGluon,gmm_random,50,0.465355,-0.002155
28,hs_06,AutoGluon,gmm_random,75,0.577597,-0.000615
29,hs_06,AutoGluon,gmm_random,50,0.578212,-0.000173
30,ua_03,AutoGluon,gmm_random,75,0.566463,-0.000163

### 0-100 diff (equal)

In [ ]:
da_analysis_equal = result_equal[result_equal["percentage"].isin([0, 100])] # or result_equal since it has the same effect
da_analysis_equal = da_analysis_equal.merge(da_analysis_equal, on=["predicted_dataset", "automl_system", "method"])
da_analysis_equal = da_analysis_equal[
    (da_analysis_equal["percentage_x"] != da_analysis_equal["percentage_y"])
]
da_analysis_equal = da_analysis_equal.drop_duplicates(["predicted_dataset", "automl_system", "method"])
da_analysis_equal["diff"] = da_analysis_equal["hold_out_f1_score_y"] - da_analysis_equal["hold_out_f1_score_x"]
da_analysis_equal.sort_values("diff", ignore_index=True)

,predicted_dataset,automl_system,method,percentage_x,hold_out_f1_score_x,is_monotonic_increasing_x,percentage_y,hold_out_f1_score_y,is_monotonic_increasing_y,diff
0,hs_06,AutoGluon,gmm_random,0,0.588944,False,100,0.579677,False,-0.009266
1,ua_03,AutoGluon,gmm_random,0,0.608699,False,100,0.666667,False,0.057967
2,hs_04,AutoGluon,gmm_random,0,0.830148,True,100,0.925574,True,0.095426
3,fn_06,AutoGluon,gmm_random,0,0.362869,False,100,0.459916,False,0.097046
4,hs_10,AutoGluon,gmm_random,0,0.602222,False,100,0.700000,False,0.097778
5,pc_02,AutoGluon,gmm_random,0,0.595963,False,100,0.694051,False,0.098088
6,ua_01,AutoGluon,gmm_random,0,0.552515,True,100,0.658105,True,0.105590
7,pc_05,AutoGluon,gmm_random,0,0.467868,False,100,0.573810,False,0.105942
8,hs_09,AutoGluon,gmm_random,0,0.842219,True,100,0.949919,True,0.107701
9,pc_08,AutoGluon,gmm_random,0,0.371456,False,100,0.483202,False,0.111746
10,fn_07,AutoGluon,gmm_random,0,0.394886,True,100,0.522727,True,0.127841
11,ua_05,AutoGluon,gmm_random,0,0.657960,True,100,0.788557,True,0.130597
12,hs_08,AutoGluon,gmm_random,0,0.816324,True,100,0.956007,True,0.139683
13,ua_06,AutoGluon,gmm_random,0,0.438842,True,100,0.588321,True,0.149480
14,fn_02,AutoGluon,gmm_random,0,0.344444,False,100,0.500000,False,0.155556
15,hs_03,AutoGluon,gmm_random,0,0.584734,True,100,0.768908,True,0.184174
16,fn_09,AutoGluon,gmm_random,0,0.285834,False,100,0.471081,False,0.185247
17,fn_10,AutoGluon,gmm_random,0,0.366667,True,100,0.583333,True,0.216667
18,hs_12,AutoGluon,gmm_random,0,0.441441,True,100,0.675676,True,0.234234
19,pc_03,AutoGluon,gmm_random,0,0.591593,True,100,0.841734,True,0.250141
20,sd_04,AutoGluon,gmm_random,0,0.370667,True,100,0.624000,True,0.253333
21,pc_01,AutoGluon,gmm_random,0,0.525567,True,100,0.783184,True,0.257617
22,pc_06,AutoGluon,gmm_random,0,0.615353,False,100,0.881172,False,0.265820
23,pc_04,AutoGluon,gmm_random,0,0.593892,False,100,0.860282,False,0.266390
24,sd_03,AutoGluon,gmm_random,0,0.333333,True,100,0.610667,True,0.277333
25,ua_04,AutoGluon,gmm_random,0,0.236497,True,100,0.517804,True,0.281306
26,pc_07,AutoGluon,gmm_random,0,0.504801,False,100,0.835391,False,0.330590
27,hs_11,AutoGluon,gmm_random,0,0.472141,True,100,0.832845,True,0.360704
28,hs_01,AutoGluon,gmm_random,0,0.450348,False,100,0.834915,False,0.384567
29,hs_14,AutoGluon,gmm_random,0,0.574561,True,100,0.960526,True,0.385965
30,ed_01,AutoGluon,gmm_random,0,0.020747,False,100,0.468880,False,0.448133
31,hs_13,AutoGluon,gmm_random,0,0.366925,True,100,0.826873,True,0.459948
32,hs_02,AutoGluon,gmm_random,0,0.314387,True,100,0.848792,True,0.534404

### 0-100 diff (diff)

In [ ]:
da_analysis_diff = result_diff[result_diff["percentage"].isin([0, 100])] # or result_equal since it has the same effect
da_analysis_diff = da_analysis_diff.merge(da_analysis_diff, on=["predicted_dataset", "automl_system", "method"])
da_analysis_diff = da_analysis_diff[
    (da_analysis_diff["percentage_x"] != da_analysis_diff["percentage_y"])
]
da_analysis_diff = da_analysis_diff.drop_duplicates(["predicted_dataset", "automl_system", "method"])
da_analysis_diff["diff"] = da_analysis_diff["hold_out_f1_score_y"] - da_analysis_diff["hold_out_f1_score_x"]
da_analysis_diff.sort_values("diff", ignore_index=True)

,predicted_dataset,automl_system,method,percentage_x,hold_out_f1_score_x,is_monotonic_increasing_x,percentage_y,hold_out_f1_score_y,is_monotonic_increasing_y,diff
0,hs_06,AutoGluon,gmm_random,0,0.588944,False,100,0.579677,False,-0.009266
1,ua_03,AutoGluon,gmm_random,0,0.608699,False,100,0.666667,False,0.057967
2,hs_04,AutoGluon,gmm_random,0,0.830148,True,100,0.925574,True,0.095426
3,fn_06,AutoGluon,gmm_random,0,0.362869,False,100,0.459916,False,0.097046
4,hs_10,AutoGluon,gmm_random,0,0.602222,False,100,0.700000,False,0.097778
5,pc_02,AutoGluon,gmm_random,0,0.595963,False,100,0.694051,False,0.098088
6,ua_01,AutoGluon,gmm_random,0,0.552515,True,100,0.658105,True,0.105590
7,pc_05,AutoGluon,gmm_random,0,0.467868,False,100,0.573810,False,0.105942
8,hs_09,AutoGluon,gmm_random,0,0.842219,False,100,0.949919,False,0.107701
9,pc_08,AutoGluon,gmm_random,0,0.371456,False,100,0.483202,False,0.111746
10,fn_07,AutoGluon,gmm_random,0,0.394886,True,100,0.522727,True,0.127841
11,ua_05,AutoGluon,gmm_random,0,0.657960,False,100,0.788557,False,0.130597
12,hs_08,AutoGluon,gmm_random,0,0.816324,True,100,0.956007,True,0.139683
13,ua_06,AutoGluon,gmm_random,0,0.438842,False,100,0.588321,False,0.149480
14,fn_02,AutoGluon,gmm_random,0,0.344444,True,100,0.500000,True,0.155556
15,hs_03,AutoGluon,gmm_random,0,0.584734,False,100,0.768908,False,0.184174
16,fn_09,AutoGluon,gmm_random,0,0.285834,True,100,0.471081,True,0.185247
17,fn_10,AutoGluon,gmm_random,0,0.366667,True,100,0.583333,True,0.216667
18,hs_12,AutoGluon,gmm_random,0,0.441441,False,100,0.675676,False,0.234234
19,pc_03,AutoGluon,gmm_random,0,0.591593,False,100,0.841734,False,0.250141
20,sd_04,AutoGluon,gmm_random,0,0.370667,True,100,0.624000,True,0.253333
21,pc_01,AutoGluon,gmm_random,0,0.525567,False,100,0.783184,False,0.257617
22,pc_06,AutoGluon,gmm_random,0,0.615353,False,100,0.881172,False,0.265820
23,pc_04,AutoGluon,gmm_random,0,0.593892,False,100,0.860282,False,0.266390
24,sd_03,AutoGluon,gmm_random,0,0.333333,True,100,0.610667,True,0.277333
25,ua_04,AutoGluon,gmm_random,0,0.236497,True,100,0.517804,True,0.281306
26,pc_07,AutoGluon,gmm_random,0,0.504801,False,100,0.835391,False,0.330590
27,hs_11,AutoGluon,gmm_random,0,0.472141,True,100,0.832845,True,0.360704
28,hs_01,AutoGluon,gmm_random,0,0.450348,True,100,0.834915,True,0.384567
29,hs_14,AutoGluon,gmm_random,0,0.574561,True,100,0.960526,True,0.385965
30,ed_01,AutoGluon,gmm_random,0,0.020747,False,100,0.468880,False,0.448133
31,hs_13,AutoGluon,gmm_random,0,0.366925,False,100,0.826873,False,0.459948
32,hs_02,AutoGluon,gmm_random,0,0.314387,False,100,0.848792,False,0.534404