In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import os
files = os.listdir(
    "/content/drive/MyDrive/Colab Notebooks/output/statistics"
)
files

['sampled_all_systems.csv',
 'mistral.csv',
 'concat_flaml.csv',
 'llama.csv',
 'concat_ag.csv',
 'concat_rf.csv',
 'hpo_all_systems.csv',
 'result_equal_monotonic_rf_equal.csv',
 'result_monotonic_rf_equal.csv',
 'result_equal_monotonic_flaml_equal.csv',
 'result_monotonic_flaml_equal.csv',
 'result_equal_monotonic_ag_equal.csv',
 'result_monotonic_ag_equal.csv',
 'result_monotonic_llama.csv']

## LLAMA

In [ ]:
system = "llama"

In [ ]:
df = pd.read_csv(
    f"/content/drive/MyDrive/Colab Notebooks/output/statistics/{system}.csv",
    sep=";"
)
df

,predicted_dataset,selected_llm,number_of_examples,missing_in_pred,extra_in_pred,only_one_predicted_label,f1_micro_majority,hold_out_f1_score,y_true_labels,y_pred_labels
0,ed_01,LLAMA_3_2_3B_INSTRUCT,5,set(),set(),False,0.307054,0.448133,"['sadness', 'joy', 'surprise', 'fear', 'anger'...","['sadness', 'joy', 'surprise', 'fear', 'anger'..."
1,ed_01,LLAMA_3_2_3B_INSTRUCT,0,set(),{'---'},False,0.307054,0.381743,"['sadness', 'joy', 'surprise', 'fear', 'anger'...","['---', 'sadness', 'joy', 'surprise', 'fear', ..."
2,ed_02,LLAMA_3_2_3B_INSTRUCT,5,set(),"{'displeasure', 'loyalty', 'blues', 'rebelliou...",False,0.342871,0.548434,"['sadness', 'joy', 'surprise', 'fear', 'love',...","['displeasure', 'loyalty', 'blues', 'rebelliou..."
3,ed_02,LLAMA_3_2_3B_INSTRUCT,0,set(),"{'meh', 'embarrassment', 'irritation', 'happin...",False,0.342871,0.567734,"['sadness', 'joy', 'surprise', 'fear', 'love',...","['meh', 'sadness', 'reluctance', 'embarrassmen..."
4,ed_03,LLAMA_3_2_3B_INSTRUCT,5,set(),"{'pain', '#disapproval', 'resilience', 'irrele...",False,0.294867,0.174021,"['sadness', 'embarrassment', 'excitement', 'an...","['excitement', 'dislike', 'self-criticism', 'j..."
...,...,...,...,...,...,...,...,...,...,...
91,ua_04,LLAMA_3_2_3B_INSTRUCT,0,set(),"{'---', '4', '2'}",False,0.200040,0.373475,"['3', '5', '10', '1', '7']","['3', '---', '4', '5', '2', '10', '1', '7']"
92,ua_05,LLAMA_3_2_3B_INSTRUCT,5,set(),{'---'},False,0.776119,0.303483,"['3', '5', '10', '1', '7']","['3', '---', '5', '10', '1', '7']"
93,ua_05,LLAMA_3_2_3B_INSTRUCT,0,set(),"{'---', '500'}",False,0.776119,0.141791,"['3', '5', '10', '1', '7']","['3', '---', '5', '500', '10', '1', '7']"
94,ua_06,LLAMA_3_2_3B_INSTRUCT,5,set(),{'4'},False,0.442095,0.397528,"['3', '5', '10', '1', '7']","['3', '4', '5', '10', '1', '7']"
95,ua_06,LLAMA_3_2_3B_INSTRUCT,0,set(),{'---'},False,0.442095,0.405986,"['3', '5', '10', '1', '7']","['3', '---', '5', '10', '1', '7']"

In [ ]:
# Looking at one dataset example
df.query("predicted_dataset == 'ua_01'")

,predicted_dataset,selected_llm,number_of_examples,missing_in_pred,extra_in_pred,only_one_predicted_label,f1_micro_majority,hold_out_f1_score,y_true_labels,y_pred_labels
84,ua_01,LLAMA_3_2_3B_INSTRUCT,5,set(),"{'---', '4', 'nan', '#1', 'gd', 'helpful', 'ex...",False,0.55838,0.178081,"['3', '5', '10', '1', '7']","['3', '---', '4', '5', 'nan', '#1', 'gd', '10'..."
85,ua_01,LLAMA_3_2_3B_INSTRUCT,0,set(),{'---'},False,0.55838,0.209697,"['3', '5', '10', '1', '7']","['3', '---', '5', '10', '1', '7']"

In [ ]:
grouped_df = (
    df.groupby(
        [
            "predicted_dataset",
            "selected_llm",
        ]
    )
    .agg(
        {
            "hold_out_f1_score": "mean"
        }
    )
)
grouped_df = grouped_df.reset_index()
grouped_df

   predicted_dataset           selected_llm  hold_out_f1_score
0              ed_01  LLAMA_3_2_3B_INSTRUCT           0.414938
1              ed_02  LLAMA_3_2_3B_INSTRUCT           0.558084
2              ed_03  LLAMA_3_2_3B_INSTRUCT           0.186715
3              ed_04  LLAMA_3_2_3B_INSTRUCT           0.309968
4              ed_05  LLAMA_3_2_3B_INSTRUCT           0.291667
5              fn_01  LLAMA_3_2_3B_INSTRUCT           0.122322
6              fn_02  LLAMA_3_2_3B_INSTRUCT           0.687500
7              fn_03  LLAMA_3_2_3B_INSTRUCT           0.178929
8              fn_04  LLAMA_3_2_3B_INSTRUCT           0.105832
9              fn_05  LLAMA_3_2_3B_INSTRUCT           0.381838
10             fn_06  LLAMA_3_2_3B_INSTRUCT           0.540084
11             fn_07  LLAMA_3_2_3B_INSTRUCT           0.379261
12             fn_08  LLAMA_3_2_3B_INSTRUCT           0.069261
13             fn_09  LLAMA_3_2_3B_INSTRUCT           0.354987
14             fn_10  LLAMA_3_2_3B_INSTRUCT           0.308333
15             hs_01  LLAMA_3_2_3B_INSTRUCT           0.669197
16             hs_02  LLAMA_3_2_3B_INSTRUCT           0.688605
17             hs_03  LLAMA_3_2_3B_INSTRUCT           0.775210
18             hs_04  LLAMA_3_2_3B_INSTRUCT           0.817071
19             hs_05  LLAMA_3_2_3B_INSTRUCT           0.604948
20             hs_06  LLAMA_3_2_3B_INSTRUCT           0.564801
21             hs_07  LLAMA_3_2_3B_INSTRUCT           0.639151
22             hs_08  LLAMA_3_2_3B_INSTRUCT           0.907827
23             hs_09  LLAMA_3_2_3B_INSTRUCT           0.815832
24             hs_10  LLAMA_3_2_3B_INSTRUCT           0.653333
25             hs_11  LLAMA_3_2_3B_INSTRUCT           0.856305
26             hs_12  LLAMA_3_2_3B_INSTRUCT           0.479730
27             hs_13  LLAMA_3_2_3B_INSTRUCT           0.334625
28             hs_14  LLAMA_3_2_3B_INSTRUCT           0.603070
29             hs_15  LLAMA_3_2_3B_INSTRUCT           0.138475
30             pc_01  LLAMA_3_2_3B_INSTRUCT           0.825461
31             pc_02  LLAMA_3_2_3B_INSTRUCT           0.837110
32             pc_03  LLAMA_3_2_3B_INSTRUCT           0.750968
33             pc_04  LLAMA_3_2_3B_INSTRUCT           0.837394
34             pc_05  LLAMA_3_2_3B_INSTRUCT           0.542350
35             pc_06  LLAMA_3_2_3B_INSTRUCT           0.749358
36             pc_07  LLAMA_3_2_3B_INSTRUCT           0.513374
37             pc_08  LLAMA_3_2_3B_INSTRUCT           0.245890
38             pc_09  LLAMA_3_2_3B_INSTRUCT           0.459135
39             sd_01  LLAMA_3_2_3B_INSTRUCT           0.588542
40             sd_03  LLAMA_3_2_3B_INSTRUCT           0.369333
41             sd_04  LLAMA_3_2_3B_INSTRUCT           0.385333
42             ua_01  LLAMA_3_2_3B_INSTRUCT           0.193889
43             ua_02  LLAMA_3_2_3B_INSTRUCT           0.139569
44             ua_03  LLAMA_3_2_3B_INSTRUCT           0.323740
45             ua_04  LLAMA_3_2_3B_INSTRUCT           0.346769
46             ua_05  LLAMA_3_2_3B_INSTRUCT           0.222637
47             ua_06  LLAMA_3_2_3B_INSTRUCT           0.401757

### Result

In [ ]:
monotonic = (
    df.sort_values(
        [
            "predicted_dataset",
            "selected_llm",
            "number_of_examples",
        ]
    )
    .groupby(
        [
            "predicted_dataset",
            "selected_llm",
        ],
        as_index=False,
        observed=True
    )
    ["hold_out_f1_score"]
    .apply(lambda x: x.is_monotonic_increasing)
    .rename(columns={"hold_out_f1_score": "is_monotonic_increasing"})
    [["predicted_dataset", "selected_llm", "is_monotonic_increasing"]]
)
result = (
    monotonic.merge(
        df,
        on=["predicted_dataset", "selected_llm"],
    )
    .sort_values(["predicted_dataset", "selected_llm"])
)

result.to_csv(
    f"/content/drive/MyDrive/Colab Notebooks/output/statistics/result_monotonic_{system}.csv",
    sep=";"
)
result

,predicted_dataset,selected_llm,is_monotonic_increasing,number_of_examples,missing_in_pred,extra_in_pred,only_one_predicted_label,f1_micro_majority,hold_out_f1_score,y_true_labels,y_pred_labels
0,ed_01,LLAMA_3_2_3B_INSTRUCT,True,5,set(),set(),False,0.307054,0.448133,"['sadness', 'joy', 'surprise', 'fear', 'anger'...","['sadness', 'joy', 'surprise', 'fear', 'anger'..."
1,ed_01,LLAMA_3_2_3B_INSTRUCT,True,0,set(),{'---'},False,0.307054,0.381743,"['sadness', 'joy', 'surprise', 'fear', 'anger'...","['---', 'sadness', 'joy', 'surprise', 'fear', ..."
2,ed_02,LLAMA_3_2_3B_INSTRUCT,False,5,set(),"{'displeasure', 'loyalty', 'blues', 'rebelliou...",False,0.342871,0.548434,"['sadness', 'joy', 'surprise', 'fear', 'love',...","['displeasure', 'loyalty', 'blues', 'rebelliou..."
3,ed_02,LLAMA_3_2_3B_INSTRUCT,False,0,set(),"{'meh', 'embarrassment', 'irritation', 'happin...",False,0.342871,0.567734,"['sadness', 'joy', 'surprise', 'fear', 'love',...","['meh', 'sadness', 'reluctance', 'embarrassmen..."
4,ed_03,LLAMA_3_2_3B_INSTRUCT,False,5,set(),"{'pain', '#disapproval', 'resilience', 'irrele...",False,0.294867,0.174021,"['sadness', 'embarrassment', 'excitement', 'an...","['excitement', 'dislike', 'self-criticism', 'j..."
...,...,...,...,...,...,...,...,...,...,...,...
91,ua_04,LLAMA_3_2_3B_INSTRUCT,False,0,set(),"{'---', '4', '2'}",False,0.200040,0.373475,"['3', '5', '10', '1', '7']","['3', '---', '4', '5', '2', '10', '1', '7']"
92,ua_05,LLAMA_3_2_3B_INSTRUCT,True,5,set(),{'---'},False,0.776119,0.303483,"['3', '5', '10', '1', '7']","['3', '---', '5', '10', '1', '7']"
93,ua_05,LLAMA_3_2_3B_INSTRUCT,True,0,set(),"{'---', '500'}",False,0.776119,0.141791,"['3', '5', '10', '1', '7']","['3', '---', '5', '500', '10', '1', '7']"
94,ua_06,LLAMA_3_2_3B_INSTRUCT,False,5,set(),{'4'},False,0.442095,0.397528,"['3', '5', '10', '1', '7']","['3', '4', '5', '10', '1', '7']"
95,ua_06,LLAMA_3_2_3B_INSTRUCT,False,0,set(),{'---'},False,0.442095,0.405986,"['3', '5', '10', '1', '7']","['3', '---', '5', '10', '1', '7']"

# Analysis Examples

Some examples of interesting analysis below:

## Monotonic Analysis

### Monotonic increasing count

In [ ]:
is_monotonic_increasing_equal = result["is_monotonic_increasing"]

monotonic_increasing_equal = result.loc[is_monotonic_increasing_equal]
non_monotonic_increasing_equal = result.loc[~is_monotonic_increasing_equal]

print(f"Number EQUAL Monotonic increasing: {len(monotonic_increasing_equal.drop_duplicates('predicted_dataset'))}")
print(f"{monotonic_increasing_equal['predicted_dataset'].drop_duplicates().to_list()}")

print(f"Number EQUAL Non-monotonic increasing: {len(non_monotonic_increasing_equal.drop_duplicates('predicted_dataset'))}")
print(f"{non_monotonic_increasing_equal['predicted_dataset'].drop_duplicates().to_list()}")

Number EQUAL Monotonic increasing: 25
['ed_01', 'ed_04', 'ed_05', 'fn_02', 'fn_05', 'fn_06', 'fn_08', 'fn_09', 'hs_01', 'hs_02', 'hs_03', 'hs_05', 'hs_06', 'hs_07', 'hs_10', 'hs_11', 'hs_12', 'hs_13', 'hs_14', 'pc_07', 'sd_03', 'sd_04', 'ua_02', 'ua_03', 'ua_05']
Number EQUAL Non-monotonic increasing: 23
['ed_02', 'ed_03', 'fn_01', 'fn_03', 'fn_04', 'fn_07', 'fn_10', 'hs_04', 'hs_08', 'hs_09', 'hs_15', 'pc_01', 'pc_02', 'pc_03', 'pc_04', 'pc_05', 'pc_06', 'pc_08', 'pc_09', 'sd_01', 'ua_01', 'ua_04', 'ua_06']

### 0 and 5 hold_out_f1_score difference

In [ ]:
da_analysis = (
    result.query("number_of_examples == 0")
    .merge(
        result.query("number_of_examples == 5"),
        on=["selected_llm", "predicted_dataset"],
        suffixes=["_0", "_5"]
    )
)
da_analysis["diff"] = da_analysis["hold_out_f1_score_5"] - da_analysis["hold_out_f1_score_0"]

(
    da_analysis
    .sort_values(
        "predicted_dataset",
        ignore_index=True
    )
    [
        [
            "predicted_dataset",
            "selected_llm",
            "number_of_examples_0",
            "number_of_examples_5",
            "is_monotonic_increasing_0",
            "hold_out_f1_score_0",
            "hold_out_f1_score_5",
            "diff"
        ]
    ]
)

,predicted_dataset,selected_llm,number_of_examples_0,number_of_examples_5,is_monotonic_increasing_0,hold_out_f1_score_0,hold_out_f1_score_5,diff
0,ed_01,LLAMA_3_2_3B_INSTRUCT,0,5,True,0.381743,0.448133,0.066390
1,ed_02,LLAMA_3_2_3B_INSTRUCT,0,5,False,0.567734,0.548434,-0.019300
2,ed_03,LLAMA_3_2_3B_INSTRUCT,0,5,False,0.199409,0.174021,-0.025388
3,ed_04,LLAMA_3_2_3B_INSTRUCT,0,5,True,0.126210,0.493725,0.367515
4,ed_05,LLAMA_3_2_3B_INSTRUCT,0,5,True,0.291667,0.291667,0.000000
5,fn_01,LLAMA_3_2_3B_INSTRUCT,0,5,False,0.134788,0.109856,-0.024932
6,fn_02,LLAMA_3_2_3B_INSTRUCT,0,5,True,0.687500,0.687500,0.000000
7,fn_03,LLAMA_3_2_3B_INSTRUCT,0,5,False,0.181792,0.176066,-0.005726
8,fn_04,LLAMA_3_2_3B_INSTRUCT,0,5,False,0.113368,0.098296,-0.015072
9,fn_05,LLAMA_3_2_3B_INSTRUCT,0,5,True,0.377271,0.386405,0.009135
10,fn_06,LLAMA_3_2_3B_INSTRUCT,0,5,True,0.540084,0.540084,0.000000
11,fn_07,LLAMA_3_2_3B_INSTRUCT,0,5,False,0.414773,0.343750,-0.071023
12,fn_08,LLAMA_3_2_3B_INSTRUCT,0,5,True,0.047493,0.091029,0.043536
13,fn_09,LLAMA_3_2_3B_INSTRUCT,0,5,True,0.341995,0.367980,0.025985
14,fn_10,LLAMA_3_2_3B_INSTRUCT,0,5,False,0.375000,0.241667,-0.133333
15,hs_01,LLAMA_3_2_3B_INSTRUCT,0,5,True,0.652751,0.685642,0.032891
16,hs_02,LLAMA_3_2_3B_INSTRUCT,0,5,True,0.650466,0.726745,0.076279
17,hs_03,LLAMA_3_2_3B_INSTRUCT,0,5,True,0.745798,0.804622,0.058824
18,hs_04,LLAMA_3_2_3B_INSTRUCT,0,5,False,0.872489,0.761654,-0.110835
19,hs_05,LLAMA_3_2_3B_INSTRUCT,0,5,True,0.500000,0.709897,0.209897
20,hs_06,LLAMA_3_2_3B_INSTRUCT,0,5,True,0.556984,0.572617,0.015633
21,hs_07,LLAMA_3_2_3B_INSTRUCT,0,5,True,0.576651,0.701651,0.125000
22,hs_08,LLAMA_3_2_3B_INSTRUCT,0,5,False,0.910451,0.905203,-0.005248
23,hs_09,LLAMA_3_2_3B_INSTRUCT,0,5,False,0.873990,0.757674,-0.116317
24,hs_10,LLAMA_3_2_3B_INSTRUCT,0,5,True,0.653333,0.653333,0.000000
25,hs_11,LLAMA_3_2_3B_INSTRUCT,0,5,True,0.856305,0.856305,0.000000
26,hs_12,LLAMA_3_2_3B_INSTRUCT,0,5,True,0.459459,0.500000,0.040541
27,hs_13,LLAMA_3_2_3B_INSTRUCT,0,5,True,0.196382,0.472868,0.276486
28,hs_14,LLAMA_3_2_3B_INSTRUCT,0,5,True,0.578947,0.627193,0.048246
29,hs_15,LLAMA_3_2_3B_INSTRUCT,0,5,False,0.169259,0.107691,-0.061568
30,pc_01,LLAMA_3_2_3B_INSTRUCT,0,5,False,0.837034,0.813888,-0.023146
31,pc_02,LLAMA_3_2_3B_INSTRUCT,0,5,False,0.844193,0.830028,-0.014164
32,pc_03,LLAMA_3_2_3B_INSTRUCT,0,5,False,0.916774,0.585161,-0.331613
33,pc_04,LLAMA_3_2_3B_INSTRUCT,0,5,False,0.931573,0.743214,-0.188358
34,pc_05,LLAMA_3_2_3B_INSTRUCT,0,5,False,0.574617,0.510083,-0.064533
35,pc_06,LLAMA_3_2_3B_INSTRUCT,0,5,False,0.955095,0.543620,-0.411475
36,pc_07,LLAMA_3_2_3B_INSTRUCT,0,5,True,0.452675,0.574074,0.121399
37,pc_08,LLAMA_3_2_3B_INSTRUCT,0,5,False,0.349535,0.142244,-0.207291
38,pc_09,LLAMA_3_2_3B_INSTRUCT,0,5,False,0.538462,0.379808,-0.158654
39,sd_01,LLAMA_3_2_3B_INSTRUCT,0,5,False,0.770833,0.406250,-0.364583
40,sd_03,LLAMA_3_2_3B_INSTRUCT,0,5,True,0.336000,0.402667,0.066667
41,sd_04,LLAMA_3_2_3B_INSTRUCT,0,5,True,0.362667,0.408000,0.045333
42,ua_01,LLAMA_3_2_3B_INSTRUCT,0,5,False,0.209697,0.178081,-0.031616
43,ua_02,LLAMA_3_2_3B_INSTRUCT,0,5,True,0.127326,0.151812,0.024486
44,ua_03,LLAMA_3_2_3B_INSTRUCT,0,5,True,0.250407,0.397073,0.146667
45,ua_04,LLAMA_3_2_3B_INSTRUCT,0,5,False,0.373475,0.320064,-0.053411
46,ua_05,LLAMA_3_2_3B_INSTRUCT,0,5,True,0.141791,0.303483,0.161692
47,ua_06,LLAMA_3_2_3B_INSTRUCT,0,5,False,0.405986,0.397528,-0.008458